//  布局结构图片映射
export const layoutImgMap = {
    logicalStructure: require('@/assets/simpleMindMap/img/logicalStructure.png'),
    mindMap: require('@/assets/simpleMindMap/img/mindMap.png'),
    organizationStructure: require('@/assets/simpleMindMap/img/organizationStructure.png'),
    catalogOrganization: require('@/assets/simpleMindMap/img/catalogOrganization.png'),
    timeline: require('@/assets/simpleMindMap/img/timeline.png'),
    timeline2: require('@/assets/simpleMindMap/img/timeline2.png'),
    fishbone: require('@/assets/simpleMindMap/img/fishbone.png'),
    verticalTimeline: require('@/assets/simpleMindMap/img/verticalTimeline.png'),
}

//  主题图片映射
export const themeMap = {
    default: require('@/assets/simpleMindMap/img/default.jpg'),
    classic: require('@/assets/simpleMindMap/img/classic.jpg'),
    minions: require('@/assets/simpleMindMap/img/minions.jpg'),
    pinkGrape: require('@/assets/simpleMindMap/img/pinkGrape.jpg'),
    mint: require('@/assets/simpleMindMap/img/mint.jpg'),
    gold: require('@/assets/simpleMindMap/img/gold.jpg'),
    vitalityOrange: require('@/assets/simpleMindMap/img/vitalityOrange.jpg'),
    greenLeaf: require('@/assets/simpleMindMap/img/greenLeaf.jpg'),
    dark2: require('@/assets/simpleMindMap/img/dark2.jpg'),
    skyGreen: require('@/assets/simpleMindMap/img/skyGreen.jpg'),
    classic2: require('@/assets/simpleMindMap/img/classic2.jpg'),
    classic3: require('@/assets/simpleMindMap/img/classic3.jpg'),
    classic4: require('@/assets/simpleMindMap/img/classic4.jpg'),
    classicGreen: require('@/assets/simpleMindMap/img/classicGreen.jpg'),
    classicBlue: require('@/assets/simpleMindMap/img/classicBlue.jpg'),
    blueSky: require('@/assets/simpleMindMap/img/blueSky.jpg'),
    brainImpairedPink: require('@/assets/simpleMindMap/img/brainImpairedPink.jpg'),
    dark: require('@/assets/simpleMindMap/img/dark.jpg'),
    earthYellow: require('@/assets/simpleMindMap/img/earthYellow.jpg'),
    freshGreen: require('@/assets/simpleMindMap/img/freshGreen.jpg'),
    freshRed: require('@/assets/simpleMindMap/img/freshRed.jpg'),
    romanticPurple: require('@/assets/simpleMindMap/img/romanticPurple.jpg'),
    simpleBlack: require('@/assets/simpleMindMap/img/simpleBlack.jpg'),
    courseGreen: require('@/assets/simpleMindMap/img/courseGreen.jpg'),
    coffee: require('@/assets/simpleMindMap/img/coffee.jpg'),
    redSpirit: require('@/assets/simpleMindMap/img/redSpirit.jpg'),
    blackHumour: require('@/assets/simpleMindMap/img/blackHumour.jpg'),
    lateNightOffice: require('@/assets/simpleMindMap/img/lateNightOffice.jpg'),
    blackGold: require('@/assets/simpleMindMap/img/blackGold.jpg'),
    autumn: require('@/assets/simpleMindMap/img/autumn.jpg'),
    avocado: require('@/assets/simpleMindMap/img/avocado.jpg'),
    orangeJuice: require('@/assets/simpleMindMap/img/orangeJuice.jpg'),
}
